version: "3.8"

services:
  agent:
    build:
      context: ./my-agentica-project
      dockerfile: Dockerfile.dev
    container_name: agent
    ports:
      - "3001:3001"
    volumes:
      - ./my-agentica-project:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm run dev"
    env_file:
      - ./.env
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - CHOKIDAR_USEPOLLING=true

  backend:
    build:
      context: .
      dockerfile: ./backend/Dockerfile.dev
    container_name: oda-backend
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app/backend
    command: ./gradlew bootRun
    environment:
      - AGENT_SERVER_URL=http://agent:3001
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - SPRING_DATASOURCE_URL=${DB_URL}
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
      - OAUTH_REDIRECT_URI=${OAUTH_REDIRECT_URI}
    depends_on:
      - agent

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - backend
